### ISSUE TITLE
How can I use this with Babel / es6?

### ISSUE THREAD

**Issue by nilsboy** [scramjs/scram-engine#21]
Electron can be convinced to use Babel by using:

bootwithbabel.js:
require('babel-polyfill')
require('babel-register')
electron bootwithbabel.js ./node_modules/scram-engine/main.js app/server/index.html

This does not seem to reach the html page though.

Can this be done?

Thanx.

**Comment by lastmjs** [comment]
I think the problem is that the `require('babel-register')` is only being applied to the main.js script, which is run on the main Electron process. You need all requires in the renderer process to be affected by the `babel-register`, which means you need to run `require('babel-register')` in the context of the HTML and all of its JS. You can try editing `require-config.js` in the root directory of the project. Put `require('babel-polyfill')` and `require('babel-register')` at the very top of the file. That might work.

Otherwise, you can of course use babel to transpile your JS files beforehand, and then anything imported from the renderer process through the HTML should work.

Also, I use es6 and TypeScript with scram-engine with this tool: https://github.com/lastmjs/es-no-build
It will transpile TypeScript, es6, async/await, and es6 modules down to ES5, which is pretty much everything I need and probably most people need. You don't have to write in TypeScript, but you can if you want.

**Comment by lastmjs** [comment]
Hmmm...look at this: https://nodejs.org/api/globals.html#globals_require_extensions

Looking through the `babel-register` source code, it looks like it uses `require_extensions` under the hood to attach the transpilation functionality. From the link above, you can see that that functionality is deprecated. I would suggest moving away from using `babel-register`. I will likely never support its use officially in `scram-engine`. So either transpile your files beforehand, use https://github.com/lastmjs/es-no-build, or figure out another way to transpile on the fly. I really think `es-no-build` is a good solution though, like I said I've been using it, and on multiple projects.

**Comment by nilsboy** [comment]
I'll just go with transpiling my JS files beforehand like you suggested.

Thanx.
